import os
from dotenv import load_dotenv


load_dotenv()

def _env_bool(name: str, default: str = "false") -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


GROQ_API_KEY = os.getenv("GROQ_API_KEY")

USE_CANDIDATE_PIPELINE = _env_bool("USE_CANDIDATE_PIPELINE")
UML_GENERATION_MODE = os.getenv("UML_GENERATION_MODE", "baseline").strip().lower()
GENERATION_PROVIDER = os.getenv("GENERATION_PROVIDER", os.getenv("LLM_PROVIDER", "groq"))
GENERATION_MODEL_1 = "qwen/qwen3.6-27b"
GENERATION_MODEL_2 = "openai/gpt-oss-20b"
GENERATION_MODEL_3 = "qwen/qwen3.6-27b"

EXPERT_PROVIDER = os.getenv("EXPERT_PROVIDER", "groq")
EXPERT_MODEL = "openai/gpt-oss-120b"

EXPERT_REVIEW_PROVIDER = os.getenv("EXPERT_REVIEW_PROVIDER", EXPERT_PROVIDER)
EXPERT_REVIEW_MODEL = os.getenv("EXPERT_REVIEW_MODEL", EXPERT_MODEL)
EXPERT_REVIEW_TEMPERATURE = float(os.getenv("EXPERT_REVIEW_TEMPERATURE", "0"))
EXPERT_REVIEW_MAX_TOKENS = int(os.getenv("EXPERT_REVIEW_MAX_TOKENS", "1500"))

EXPERT_REPAIR_PROVIDER = os.getenv("EXPERT_REPAIR_PROVIDER", EXPERT_REVIEW_PROVIDER)
EXPERT_REPAIR_MODEL = os.getenv("EXPERT_REPAIR_MODEL", EXPERT_REVIEW_MODEL)
EXPERT_REPAIR_TEMPERATURE = float(os.getenv("EXPERT_REPAIR_TEMPERATURE", "0"))
EXPERT_REPAIR_MAX_TOKENS = int(os.getenv("EXPERT_REPAIR_MAX_TOKENS", "3500"))
MAX_AGENT_ITERATIONS = int(os.getenv("MAX_AGENT_ITERATIONS", "3"))

# Candidate 01
CANDIDATE_1_PROVIDER = os.getenv("CANDIDATE_1_PROVIDER", GENERATION_PROVIDER)
CANDIDATE_1_MODEL = os.getenv("CANDIDATE_1_MODEL", GENERATION_MODEL_1)
CANDIDATE_1_TEMPERATURE = float(os.getenv("CANDIDATE_1_TEMPERATURE", "0"))
CANDIDATE_1_MAX_TOKENS = int(os.getenv("CANDIDATE_1_MAX_TOKENS", "3500"))

# Candidate 02
CANDIDATE_2_PROVIDER = os.getenv("CANDIDATE_2_PROVIDER", GENERATION_PROVIDER)
CANDIDATE_2_MODEL = os.getenv("CANDIDATE_2_MODEL", GENERATION_MODEL_2)
CANDIDATE_2_TEMPERATURE = float(os.getenv("CANDIDATE_2_TEMPERATURE", "0"))
CANDIDATE_2_MAX_TOKENS = int(os.getenv("CANDIDATE_2_MAX_TOKENS", "3500"))

# Candidate 03
CANDIDATE_3_PROVIDER = os.getenv("CANDIDATE_3_PROVIDER", GENERATION_PROVIDER)
CANDIDATE_3_MODEL = os.getenv("CANDIDATE_3_MODEL", GENERATION_MODEL_3)
CANDIDATE_3_TEMPERATURE = float(os.getenv("CANDIDATE_3_TEMPERATURE", "0"))
CANDIDATE_3_MAX_TOKENS = int(os.getenv("CANDIDATE_3_MAX_TOKENS", "3500"))

MAX_ITERATIONS = int(os.getenv("MAX_ITERATIONS", "3"))
MAX_REPAIR_ATTEMPTS = int(os.getenv("MAX_REPAIR_ATTEMPTS", "2"))

# Backward-compatible config values used elsewhere
MAX_RETRY_ITERATIONS = int(os.getenv("MAX_RETRY_ITERATIONS", str(MAX_ITERATIONS)))
CONSISTENCY_SCORE_THRESHOLD = float(os.getenv("CONSISTENCY_SCORE_THRESHOLD", "0.85"))

# Prompt profile controls
PROMPT_PROFILE = os.getenv("PROMPT_PROFILE", "")
MAX_REQUIREMENT_DESCRIPTION_CHARS = int(
    os.getenv("MAX_REQUIREMENT_DESCRIPTION_CHARS", "900")
)

# Prompt size controls
MAX_VALIDATION_ERRORS = int(os.getenv("MAX_VALIDATION_ERRORS", "6"))
MAX_ERROR_BLOCK_CHARS = int(os.getenv("MAX_ERROR_BLOCK_CHARS", "1800"))
MAX_ERROR_MESSAGE_CHARS = int(os.getenv("MAX_ERROR_MESSAGE_CHARS", "200"))
MAX_ERROR_SUGGESTION_CHARS = int(os.getenv("MAX_ERROR_SUGGESTION_CHARS", "160"))

MAX_EXPERT_GUIDANCE_CHARS = int(os.getenv("MAX_EXPERT_GUIDANCE_CHARS", "800"))
MAX_RETRY_ERRORS = int(os.getenv("MAX_RETRY_ERRORS", "3"))
MAX_RETRY_ERROR_CHARS = int(os.getenv("MAX_RETRY_ERROR_CHARS", "100"))
MAX_RETRY_GUIDANCE_CHARS = int(os.getenv("MAX_RETRY_GUIDANCE_CHARS", "150"))
MAX_RETRY_REQUIREMENT_DESCRIPTION_CHARS = int(
    os.getenv("MAX_RETRY_REQUIREMENT_DESCRIPTION_CHARS", "120")
)
